name: calculator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+20

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_on_start: ^0.0.1
  
  scrollable_positioned_list: ^0.2.2
  artemis: ^7.1.1-beta.1
  async: ^2.8.1
  collection: ^1.15.0-nullsafety.4
  get: ^4.6.1
  get_cli: ^1.7.1
  get_storage: ^2.0.3
  dartx: ^1.0.0
  equatable: ^2.0.3
  json_annotation: ^4.0.1
  json_serializable: ^4.1.4
  jwt_decoder: ^2.0.1
  dart_date: ^1.1.0
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^4.2.1

  dio: ^4.0.4
  
  uuid: ^3.0.4
  url_launcher: ^6.0.10

  mask_text_input_formatter: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  story_view: ^0.13.1

  google_fonts: ^2.1.0

  evil_icons_flutter: ^0.5.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0

  gql_dio_link: ^0.1.0
  intl: ^0.17.0
  graphql_flutter: ^5.0.0

  package_info: ^2.0.2

  pretty_dio_logger: ^1.2.0-beta-1
  connectivity_plus: ^2.2.0
  math_expressions: ^2.3.0

dev_dependencies:
  build_runner: ^2.1.1
  dart_code_metrics: ^4.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
#  assets:
#    - assets/images/


analyzer:
  plugins:
    - dart_code_metrics


dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
